// Large dataset of Quiz Questions for Classes 9-12
// Topics: Mathematics, Science (Physics, Chemistry, Biology), English, Social Science
// Used by DailyQuiz component in app.js

const ALL_QUIZ_QUESTIONS = {
    9: [
        // Mathematics
        { question: "What is the value of π (pi) approximately?", options: ["3.14", "2.71", "1.41", "4.56"], correct: 0 },
        { question: "What is 15 × 8?", options: ["100", "120", "110", "130"], correct: 1 },
        { question: "What is the square root of 64?", options: ["6", "7", "8", "9"], correct: 2 },
        { question: "What is the smallest prime number?", options: ["0", "1", "2", "3"], correct: 2 },
        { question: "Calculate the area of a rectangle with length 5cm and width 3cm.", options: ["8 cm²", "15 cm²", "16 cm²", "53 cm²"], correct: 1 },
        { question: "Which of these is an irrational number?", options: ["√4", "√9", "√16", "√2"], correct: 3 },
        { question: "The sum of angles in a triangle is?", options: ["90°", "180°", "360°", "270°"], correct: 1 },
        { question: "x + 5 = 12. Find x.", options: ["5", "6", "7", "8"], correct: 2 },
        { question: "Which is a polynomial?", options: ["x + 1/x", "√x + 3", "x² + 2x", "x⁻¹ + 5"], correct: 2 },
        { question: "Volume of a cube with side 'a' is?", options: ["a²", "a³", "3a", "6a²"], correct: 1 },
        { question: "Perimeter of a circle is called?", options: ["Area", "Circumference", "Diameter", "Radius"], correct: 1 },
        { question: "Complementary angle of 40° is?", options: ["40°", "50°", "140°", "90°"], correct: 1 },
        { question: "Supplementary angle of 100° is?", options: ["80°", "10°", "260°", "100°"], correct: 0 },
        { question: "Point (3, -2) lies in which quadrant?", options: ["I", "II", "III", "IV"], correct: 3 },
        { question: "0 is a ______ number.", options: ["Positive", "Negative", "Neutral", "Imaginary"], correct: 2 },
        
        // Science
        { question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "NaCl"], correct: 0 },
        { question: "Which planet is closest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], correct: 1 },
        { question: "Which gas do plants absorb from the atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 1 },
        { question: "The fundamental unit of life is?", options: ["Tissue", "Organ", "Cell", "Atom"], correct: 2 },
        { question: "SI unit of force is?", options: ["Pascal", "Joule", "Newton", "Watt"], correct: 2 },
        { question: "Is matter around us pure? (Chapter)", options: ["Yes", "No", "Maybe", "Sometimes"], correct: 1 },
        { question: "Boiling point of water is?", options: ["0°C", "50°C", "100°C", "200°C"], correct: 2 },
        { question: "Which organelle is called the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Lysosome"], correct: 1 },
        { question: "Speed is defined as?", options: ["Distance/Time", "Time/Distance", "Distance × Time", "Force × Mass"], correct: 0 },
        { question: "Law of Inertia is Newton's ___ Law.", options: ["First", "Second", "Third", "Fourth"], correct: 0 },
        { question: "Atomic number of Carbon is?", options: ["6", "12", "14", "8"], correct: 0 },
        { question: "Symbol for Sodium is?", options: ["S", "So", "Na", "Sd"], correct: 2 },
        { question: "Valency of Oxygen is?", options: ["1", "2", "3", "4"], correct: 1 },
        { question: "Xylem transports ___ in plants.", options: ["Food", "Water", "Air", "Sunlight"], correct: 1 },
        { question: "Phloem transports ___ in plants.", options: ["Food", "Water", "Minerals", "Oils"], correct: 0 },
        
        // English & General
        { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correct: 1 },
        { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
        { question: "Identify the noun: 'He runs fast.'", options: ["He", "runs", "fast", "None"], correct: 3 }, 
        { question: "Past tense of 'Go' is?", options: ["Gone", "Went", "Going", "Goes"], correct: 1 },
        { question: "Synonym of 'Beautiful' is?", options: ["Ugly", "Pretty", "Bad", "Sad"], correct: 1 },
        { question: "Antonym of 'Hot' is?", options: ["Warm", "Cold", "Boiling", "Fire"], correct: 1 },
        { question: "Which is a vowel?", options: ["B", "C", "I", "T"], correct: 2 },
        { question: "Capital of France?", options: ["London", "Berlin", "Paris", "Rome"], correct: 2 },
        { question: "National animal of India?", options: ["Lion", "Tiger", "Elephant", "Peacock"], correct: 1 },
        { question: "Currency of USA?", options: ["Euro", "Rupee", "Dollar", "Pound"], correct: 2 },
        { question: "Who is the 'Father of the Nation' in India?", options: ["Nehru", "Gandhi", "Modi", "Ambedkar"], correct: 1 },
        { question: "How many states are in India?", options: ["28", "29", "25", "30"], correct: 0 },
        { question: "Which day is Republic Day?", options: ["15 Aug", "26 Jan", "2 Oct", "14 Nov"], correct: 1 },
        { question: "Brain of the computer is?", options: ["Mouse", "CPU", "Monitor", "Keyboard"], correct: 1 },
        { question: "RAM stands for?", options: ["Read Access Memory", "Random Access Memory", "Run All Memory", "None"], correct: 1 }
    ],
    10: [
        // Mathematics
        { question: "What is the formula for the area of a circle?", options: ["πr²", "2πr", "πd", "r²"], correct: 0 },
        { question: "What is the value of sin(90°)?", options: ["0", "0.5", "1", "√2/2"], correct: 2 },
        { question: "What is the derivative of x²?", options: ["x", "2x", "x²", "2x²"], correct: 1 }, // Note: Calculus starts later usually, but basic slope concept might be there. Removing if too advanced, but standard quiz usually allows simple power rule.
        { question: "Roots of x² - 9 = 0 are?", options: ["3, 3", "3, -3", "-3, -3", "9, -9"], correct: 1 },
        { question: "HCF of 8 and 12 is?", options: ["2", "4", "8", "24"], correct: 1 },
        { question: "Sum of roots of ax² + bx + c = 0 is?", options: ["b/a", "-b/a", "c/a", "-c/a"], correct: 1 },
        { question: "Product of roots of quadratic eq is?", options: ["c/a", "-c/a", "b/a", "-b/a"], correct: 0 },
        { question: "Distance between (0,0) and (3,4) is?", options: ["4", "5", "7", "12"], correct: 1 },
        { question: "Value of tan(45°)?", options: ["0", "1", "√3", "1/√3"], correct: 1 },
        { question: "Sec²θ - Tan²θ = ?", options: ["0", "1", "-1", "2"], correct: 1 },
        { question: "Probability of an impossible event is?", options: ["0", "1", "0.5", "-1"], correct: 0 },
        { question: "Probability of a sure event is?", options: ["0", "1", "100", "0.1"], correct: 1 },
        { question: "Mode of 2, 3, 2, 4, 2, 5 is?", options: ["2", "3", "4", "5"], correct: 0 },
        { question: "Nth term of AP difference formula?", options: ["a+(n-1)d", "a+nd", "a(n-1)d", "an+d"], correct: 0 },
        { question: "Volume of a cylinder?", options: ["2πrh", "πr²h", "πrh", "2πr"], correct: 1 },

        // Science
        { question: "What is the chemical formula for glucose?", options: ["C6H12O6", "H2O", "CO2", "NaCl"], correct: 0 },
        { question: "Who discovered the law of gravity?", options: ["Einstein", "Newton", "Galileo", "Darwin"], correct: 1 },
        { question: "Speed of light in vacuum?", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], correct: 0 },
        { question: "Which process do plants use to make food?", options: ["Respiration", "Photosynthesis", "Digestion", "Transpiration"], correct: 1 },
        { question: "Atomic number of Carbon?", options: ["4", "5", "6", "7"], correct: 2 },
        { question: "pH value of pure water?", options: ["5", "6", "7", "8"], correct: 2 },
        { question: "Universal donor blood group?", options: ["A", "B", "AB", "O"], correct: 3 },
        { question: "Powerhouse of cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi Body"], correct: 1 },
        { question: "Unit of electric current?", options: ["Volt", "Ampere", "Ohm", "Watt"], correct: 1 },
        { question: "Unit of resistance?", options: ["Volt", "Ampere", "Ohm", "Joule"], correct: 2 },
        { question: "Mirror formula is?", options: ["1/v + 1/u = 1/f", "1/v - 1/u = 1/f", "v + u = f", "v - u = f"], correct: 0 },
        { question: "Lens formula is?", options: ["1/v + 1/u = 1/f", "1/v - 1/u = 1/f", "1/f - 1/u = 1/v", "None"], correct: 1 },
        { question: "Chemical name of Baking Soda?", options: ["Sodium Carbonate", "Sodium Bicarbonate", "Calcium Carbonate", "Sodium Chloride"], correct: 1 },
        { question: "Hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], correct: 2 },
        { question: "Metal liquid at room temp?", options: ["Iron", "Mercury", "Copper", "Aluminum"], correct: 1 },
        
        // English & Social
        { question: "Who wrote 'The Diary of a Young Girl'?", options: ["Anne Frank", "Helen Keller", "Ruskin Bond", "R.K. Narayan"], correct: 0 },
        { question: "When did India get independence?", options: ["1945", "1947", "1950", "1952"], correct: 1 },
        { question: "First Prime Minister of India?", options: ["Gandhi", "Nehru", "Patel", "Bose"], correct: 1 },
        { question: "Which soil is best for cotton?", options: ["Red Soil", "Black Soil", "Sandy Soil", "Clay"], correct: 1 },
        { question: "Full form of GDP?", options: ["Gross Domestic Product", "General Domestic Price", "Gross Direct Product", "None"], correct: 0 },
        { question: "Highest court in India?", options: ["High Court", "District Court", "Supreme Court", "Civil Court"], correct: 2 },
        { question: "Currency of Japan?", options: ["Yen", "Yuan", "Dollar", "Won"], correct: 0 },
        { question: "Capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
        { question: "Longest river in the world?", options: ["Amazon", "Nile", "Ganga", "Yangtze"], correct: 1 },
        { question: "Which gas is filled in balloons?", options: ["Hydrogen", "Helium", "Oxygen", "Nitrogen"], correct: 1 },
        { question: "Vande Mataram was written by?", options: ["Tagore", "Bankim Chandra", "Sarojini Naidu", "Premchand"], correct: 1 },
        { question: "National Anthem duration?", options: ["52 secs", "60 secs", "45 secs", "90 secs"], correct: 0 },
        { question: "Study of maps is called?", options: ["Geography", "Cartography", "Geology", "Topology"], correct: 1 },
        { question: "Smallest continent?", options: ["Asia", "Europe", "Australia", "Africa"], correct: 2 },
        { question: "Largest desert?", options: ["Sahara", "Gobi", "Thar", "Antarctic"], correct: 3 }
    ],
    11: [
        // Mathematics
        { question: "Value of log₁₀(100)?", options: ["1", "2", "10", "100"], correct: 1 },
        { question: "Which law states F = ma?", options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Ohm's Law"], correct: 1 },
        { question: "Integral of 1/x?", options: ["x", "ln(x)", "1/x²", "x²"], correct: 1 },
        { question: "Value of tan(45°)?", options: ["0", "1", "√3", "∞"], correct: 1 },
        { question: "i² in complex numbers is?", options: ["1", "-1", "0", "i"], correct: 1 },
        { question: "Number of subsets of a set with n elements?", options: ["n", "2n", "2ⁿ", "n²"], correct: 2 },
        { question: "Domain of sin(x)?", options: ["(-1, 1)", "[-1, 1]", "R (Real numbers)", "0 to 2π"], correct: 2 },
        { question: "Range of cos(x)?", options: ["(-∞, ∞)", "[-1, 1]", "[0, 1]", "R"], correct: 1 },
        { question: "Equation of a circle?", options: ["y = mx+c", "x² + y² = r²", "y² = 4ax", "x²/a² + y²/b² = 1"], correct: 1 },
        { question: "Slope of horizontal line?", options: ["0", "1", "Undefined", "-1"], correct: 0 },
        { question: "5! (5 factorial) is?", options: ["20", "60", "100", "120"], correct: 3 },
        { question: "Combination formula ⁿCᵣ?", options: ["n!/r!", "n!/(n-r)!r!", "n!/(n-r)!", "n!r!"], correct: 1 },
        { question: "First term of GP a, ar, ar²...", options: ["a", "r", "ar", "0"], correct: 0 },
        { question: "Sum of infinite GP formula?", options: ["a/(1-r)", "a(1-r)", "ar", "∞"], correct: 0 },
        { question: "Derivative of sin(x)?", options: ["cos(x)", "-cos(x)", "tan(x)", "sec(x)"], correct: 0 },

        // Physics
        { question: "SI unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], correct: 1 },
        { question: "Dimension of Force?", options: ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "M⁰LT⁻¹"], correct: 0 },
        { question: "Scalar quantity?", options: ["Force", "Velocity", "Speed", "Acceleration"], correct: 2 },
        { question: "First equation of motion?", options: ["s = ut + ½at²", "v = u + at", "v² - u² = 2as", "F = ma"], correct: 1 },
        { question: "Value of G (Gravitational Constant)?", options: ["9.8", "6.67×10⁻¹¹", "6.022×10²³", "1.6×10⁻¹⁹"], correct: 1 },
        { question: "Hooke's Law?", options: ["F = -kx", "F = ma", "E = mc²", "P = IV"], correct: 0 },
        { question: "Unit of Work?", options: ["Newton", "Joule", "Watt", "Pascal"], correct: 1 },
        { question: "1 HP = ? Watts", options: ["746", "1000", "500", "750"], correct: 0 },
        { question: "Sound is a ___ wave.", options: ["Transverse", "Longitudinal", "Electromagnetic", "None"], correct: 1 },
        { question: "Light is a ___ wave.", options: ["Transverse", "Longitudinal", "Mechanical", "Gaseous"], correct: 0 },
        { question: "Absolute Zero temp?", options: ["0°C", "-273.15°C", "273 K", "100°C"], correct: 1 },
        { question: "First law of thermodynamics?", options: ["ΔQ = ΔU + ΔW", "F = ma", "PV = nRT", "E = hν"], correct: 0 },
        { question: "In ideal gas eq PV=nRT, R is?", options: ["Resistance", "Radius", "Gas Constant", "Rate"], correct: 2 },
        { question: "Stress is?", options: ["Force/Area", "Force × Area", "Change in L / L", "None"], correct: 0 },
        { question: "Surface tension unit?", options: ["N/m", "N/m²", "N·m", "Joule"], correct: 0 },

        // Chemistry & Bio
        { question: "Molecular formula of methane?", options: ["CH4", "C2H6", "C3H8", "CO2"], correct: 0 },
        { question: "Avogadro's number?", options: ["6.022×10²³", "6.022×10²²", "6.022×10²⁴", "6.022×10²¹"], correct: 0 },
        { question: "Gold symbol?", options: ["Go", "Gd", "Au", "Ag"], correct: 2 },
        { question: "Particle with no charge?", options: ["Proton", "Electron", "Neutron", "Ion"], correct: 2 },
        { question: "Config of Neon (Atomic No 10)?", options: ["2, 8", "2, 8, 1", "2, 6", "2, 8, 8"], correct: 0 },
        { question: "pH < 7 indicates?", options: ["Acidic", "Basic", "Neutral", "Salt"], correct: 0 },
        { question: "S-block elements are called?", options: ["Alkali metals", "Noble gases", "Halogens", "Transition metals"], correct: 0 },
        { question: "Study of Fungi?", options: ["Phycology", "Mycology", "Biology", "Zoology"], correct: 1 },
        { question: "Basic unit of classification?", options: ["Kingdom", "Class", "Species", "Family"], correct: 2 },
        { question: "Fluid mosaic model is of?", options: ["Cell Wall", "Plasma Membrane", "Nucleus", "Ribosome"], correct: 1 },
        { question: "Respiration creates?", options: ["O2", "Energy (ATP)", "Glucose", "Starch"], correct: 1 },
        { question: "Human heart has __ chambers.", options: ["2", "3", "4", "5"], correct: 2 },
        { question: "Kidney's functional unit?", options: ["Neuron", "Nephron", "Alveoli", "Villi"], correct: 1 },
        { question: "Master gland of body?", options: ["Thyroid", "Adrenal", "Pituitary", "Pancreas"], correct: 2 },
        { question: "Mendel worked on which plant?", options: ["Rose", "Pea", "Mango", "Rice"], correct: 1 }
    ],
    12: [
         // Physics
        { question: "Charge of electron?", options: ["+1.6×10⁻¹⁹ C", "-1.6×10⁻¹⁹ C", "0", "1"], correct: 1 },
        { question: "SI unit of capacitance?", options: ["Coulomb", "Volt", "Farad", "Ohm"], correct: 2 },
        { question: "Resistance of ideal ammeter?", options: ["Infinite", "Zero", "High", "Low"], correct: 1 },
        { question: "Resistance of ideal voltmeter?", options: ["Infinite", "Zero", "High", "Low"], correct: 0 },
        { question: "Magnetic field unit?", options: ["Tesla", "Weber", "Henry", "Flux"], correct: 0 },
        { question: "Len's Law is conservation of?", options: ["Mass", "Charge", "Energy", "Momentum"], correct: 2 },
        { question: "Speed of light constant?", options: ["c", "h", "G", "k"], correct: 0 },
        { question: "Photon energy formula?", options: ["E = mc²", "E = hν", "F = ma", "P = IV"], correct: 1 },
        { question: "Semiconductor example?", options: ["Copper", "Silicon", "Rubber", "Gold"], correct: 1 },
        { question: "Rectifier converts?", options: ["AC to DC", "DC to AC", "High V to Low V", "None"], correct: 0 },
        { question: "Logic gate for Addition?", options: ["AND", "OR", "NOT", "NAND"], correct: 1 }, // Technically OR is like addition
        { question: "Communication via optical fiber uses?", options: ["Refraction", "Reflection", "TIR", "Diffraction"], correct: 2 },
        { question: "Nucleus contains?", options: ["Protons only", "Neutrons only", "Protons & Neutrons", "Electrons"], correct: 2 },
        { question: "Radioactivity discovered by?", options: ["Curie", "Becquerel", "Rutherford", "Einstein"], correct: 1 },
        { question: "Transformer works on?", options: ["DC", "AC", "Both", "None"], correct: 1 },

        // Chemistry
        { question: "Example of Crystalline solid?", options: ["Glass", "Rubber", "Plastic", "NaCl"], correct: 3 },
        { question: "Molality formula?", options: ["Moles/Vol(L)", "Moles/Mass(kg)", "Mass/Vol", "None"], correct: 1 },
        { question: "Standard Electrode Potential of H?", options: ["0 V", "1 V", "-1 V", "10 V"], correct: 0 },
        { question: "Order of radioactive decay?", options: ["Zero", "First", "Second", "Third"], correct: 1 },
        { question: "Catalyst changes?", options: ["ΔG", "Equilibrium Constant", "Activation Energy", "Enthalpy"], correct: 2 },
        { question: "Process to extract Iron?", options: ["Blast Furnace", "Electrolysis", "Zone Refining", "Froth Floatation"], correct: 0 },
        { question: "Laughing Gas?", options: ["NO", "N2O", "NO2", "N2O5"], correct: 1 },
        { question: "King of Chemicals?", options: ["HCl", "H2SO4", "HNO3", "NaCl"], correct: 1 },
        { question: "Transition elements block?", options: ["s", "p", "d", "f"], correct: 2 },
        { question: "Formula of Ethanol?", options: ["CH3OH", "C2H5OH", "CH3COOH", "C6H6"], correct: 1 },
        { question: "Functional group of Alcohol?", options: ["-CHO", "-COOH", "-OH", "-CO-"], correct: 2 },
        { question: "Benzene formula?", options: ["C6H6", "C6H12", "C6H5", "CH4"], correct: 0 },
        { question: "Glucose is a ___?", options: ["Protein", "Carbohydrate", "Fat", "Vitamin"], correct: 1 },
        { question: "Vitamin C deficiency causes?", options: ["Rickets", "Scurvy", "Beriberi", "Night Blindness"], correct: 1 },
        { question: "Monomer of Polythene?", options: ["Ethane", "Ethene", "Ethyne", "Methane"], correct: 1 },

        // Math
        { question: "Order of matrix [2 3] is?", options: ["1x2", "2x1", "2x2", "1x1"], correct: 0 },
        { question: "Determinant of unit matrix?", options: ["0", "1", "-1", "undefined"], correct: 1 },
        { question: "d/dx of sin(x)?", options: ["cos x", "-cos x", "tan x", "sec x"], correct: 0 },
        { question: "d/dx of e^x?", options: ["x e^x", "e^x", "e^x / x", "ln x"], correct: 1 },
        { question: "d/dx of ln x?", options: ["1/x", "x", "e^x", "1"], correct: 0 },
        { question: "Integral of cos x?", options: ["sin x", "-sin x", "cos x", "tan x"], correct: 0 },
        { question: "Integral of 1/x?", options: ["ln|x|", "x", "-1/x^2", "e^x"], correct: 0 },
        { question: "Slope of normal if tangent slope = m?", options: ["m", "-m", "1/m", "-1/m"], correct: 3 },
        { question: "Limit of (sin x)/x as x->0?", options: ["0", "1", "inf", "-1"], correct: 1 },
        { question: "Degree of d²y/dx² + (dy/dx)³ = 0?", options: ["1", "2", "3", "0"], correct: 0 },
        { question: "Order of d²y/dx² + y = 0?", options: ["1", "2", "0", "3"], correct: 1 },
        { question: "Dot product i . j ?", options: ["0", "1", "k", "-1"], correct: 0 },
        { question: "Cross product i x j ?", options: ["0", "1", "k", "-k"], correct: 2 },
        { question: "Equation of plane?", options: ["ax+by+cz=d", "y=mx+c", "x²+y²=r²", "F=ma"], correct: 0 },
        { question: "P(A|B) is?", options: ["P(A∩B)/P(B)", "P(A∩B)/P(A)", "P(A)P(B)", "P(A)+P(B)"], correct: 0 }
    ]
};
